# Generated by Django 3.2 on 2021-05-05 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joke',
            old_name='appproved',
            new_name='approved',
        ),
    ]
