# Generated by Django 3.2 on 2021-05-05 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_rename_appproved_joke_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='joke',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
