# Generated by Django 3.2 on 2021-04-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20210428_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='joke',
            field=models.CharField(max_length=10000),
        ),
    ]
