# Generated by Django 3.2 on 2021-05-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210505_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
