# Generated by Django 3.2 on 2021-05-05 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_joke_reviewed'),
        ('main_app', '0005_remove_profile_username'),
    ]

    operations = [
    ]
