# Generated by Django 3.2 on 2021-05-01 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20210501_1818'),
        ('main_app', '0006_comment_joke'),
    ]

    operations = [
    ]
