# Generated by Django 3.2 on 2021-05-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_joke_category'),
        ('main_app', '0006_comment_joke'),
    ]

    operations = [
    ]
