# Generated by Django 3.2 on 2021-05-06 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210505_1742'),
        ('main_app', '0007_profile_moderator'),
    ]

    operations = [
    ]
