# Generated by Django 3.2 on 2021-05-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_merge_0006_auto_20210501_1818_0006_comment_joke'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='category',
            field=models.CharField(choices=[('Y', 'Yo Mama'), ('D', 'Dad'), ('H', 'Chuck Norris'), ('P', 'Pun'), ('C', 'Computer')], default='Y', max_length=50),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
