# Generated by Django 3.2 on 2021-05-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_merge_0007_auto_20210505_1742_0007_profile_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='source',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
