# Generated by Django 3.2 on 2021-05-08 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_joke_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='category',
            field=models.CharField(choices=[('R', 'Random'), ('Y', 'Yo Mama'), ('D', 'Dad'), ('H', 'Chuck Norris'), ('P', 'Pun'), ('K', 'Knock Knock'), ('B', 'Bar'), ('C', 'Computer'), ('S', 'Sports'), ('A', 'Animal')], default='R', max_length=50),
        ),
    ]
