# Generated by Django 3.2 on 2021-05-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_joke_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joke',
            name='category',
            field=models.CharField(choices=[('Y', 'Yo Mama'), ('D', 'Dad'), ('H', 'Chuck Norris'), ('P', 'Pun'), ('K', 'Knock Knock'), ('B', 'Bar'), ('C', 'Computer'), ('S', 'Sports'), ('A', 'Animal')], default='Y', max_length=50),
        ),
    ]
